# Generated by Django 5.0.6 on 2024-05-14 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('detalhes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ServicoRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCalculadora.recurso')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCalculadora.servico')),
            ],
        ),
        migrations.AddField(
            model_name='servico',
            name='recursos',
            field=models.ManyToManyField(through='AppCalculadora.ServicoRecurso', to='AppCalculadora.recurso'),
        ),
        migrations.AddField(
            model_name='recurso',
            name='tipo_recurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCalculadora.tiporecurso'),
        ),
    ]
