# Generated by Django 5.0.6 on 2024-07-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCalculadora', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='recursos',
        ),
        migrations.AddField(
            model_name='servico',
            name='modelo',
            field=models.CharField(choices=[('IAAS', 'Infrastructure as a Service (IAAS)'), ('PAAS', 'Platform as a Service (PAAS)'), ('SAAS', 'Software as a Service (SAAS)')], default='IAAS', max_length=255),
        ),
    ]
