# Generated by Django 5.0.6 on 2024-05-14 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCalculadora', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome do tipo de custo (ex: Pessoal, Energia, Licenças)', max_length=255)),
                ('descricao', models.TextField(help_text='Descrição do tipo de custo')),
            ],
        ),
        migrations.CreateModel(
            name='Custo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(help_text='Descrição detalhada do custo')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor do custo', max_digits=12)),
                ('data_inicio', models.DateField(help_text='Data de início da vigência do custo')),
                ('data_fim', models.DateField(blank=True, help_text='Data de término da vigência do custo (opcional)', null=True)),
                ('tipo_custo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custos', to='AppCalculadora.tipocusto')),
            ],
        ),
    ]
