# Generated by Django 5.0.6 on 2024-07-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCalculadora', '0002_remove_servico_recursos_servico_modelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloAssinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Valor Anual')),
            ],
        ),
    ]
