# Generated by Django 5.0.6 on 2024-05-14 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCalculadora', '0002_tipocusto_custo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComportamentoCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('exemplos', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FuncaoCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('exemplos', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='custo',
            name='data_fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='custo',
            name='data_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='custo',
            name='descricao',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='custo',
            name='tipo_custo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='custos', to='AppCalculadora.tipocusto'),
        ),
        migrations.AlterField(
            model_name='custo',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AddField(
            model_name='custo',
            name='comportamento_custo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='custos', to='AppCalculadora.comportamentocusto'),
        ),
        migrations.AddField(
            model_name='custo',
            name='funcao_custo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='custos', to='AppCalculadora.funcaocusto'),
        ),
    ]
