# Generated by Django 5.0.6 on 2024-07-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCalculadora', '0003_modeloassinatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='recursodatacenter',
            name='custo_total_aplicado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='recursodatacenter',
            name='percentual_finops',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='recursodatacenter',
            name='valor_unitario',
            field=models.CharField(default=0.0, max_length=100),
        ),
        migrations.AlterField(
            model_name='modeloassinatura',
            name='valor_desconto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Valor Anual'),
        ),
    ]
