# Generated by Django 5.0.6 on 2024-05-14 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCalculadora', '0003_comportamentocusto_funcaocusto_alter_custo_data_fim_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('endereco', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=255)),
                ('website', models.URLField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='custo',
            name='valor',
        ),
        migrations.CreateModel(
            name='EmpresaCusto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('custo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCalculadora.custo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCalculadora.empresa')),
            ],
        ),
    ]
