# Generated by Django 5.0.6 on 2024-08-08 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCalculadora', '0005_alter_recursodatacenter_custo_total_aplicado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='unidade_medida',
            field=models.CharField(choices=[(1, 'horas de CPU ANO'), (2, 'em gigabytes (GB) por mês'), (3, 'em gigabytes (GB) Transferidos por mês'), (4, 'eventos monitorados por mês')], default=1, max_length=255),
        ),
    ]
