# Generated by Django 5.0.6 on 2024-08-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCalculadora', '0006_recurso_unidade_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='unidade_medida',
            field=models.CharField(choices=[('horas de CPU ANO', 'horas de CPU ANO'), ('em gigabytes (GB) por mês', 'em gigabytes (GB) por mês'), ('em gigabytes (GB) Transferidos por mês', 'em gigabytes (GB) Transferidos por mês'), ('eventos monitorados por mês', 'eventos monitorados por mês')], default='horas de CPU ANO', max_length=255),
        ),
    ]
