# Generated by Django 5.0.6 on 2024-08-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCalculadora', '0007_alter_recurso_unidade_medida'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicorecurso',
            name='detalhe',
            field=models.CharField(default='Nada a informar', max_length=80),
        ),
    ]
