# Generated by Django 5.0.6 on 2024-08-12 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCalculadora', '0008_servicorecurso_detalhe'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicoAgrupado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(choices=[('IAAS', 'Infrastructure as a Service (IAAS)'), ('PAAS', 'Platform as a Service (PAAS)'), ('SAAS', 'Software as a Service (SAAS)')], default='IAAS', max_length=255)),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
            ],
        ),
    ]
